//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerHR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Freelancer
    {
        public Freelancer()
        {
            this.HiringOfferEmployee = new HashSet<HiringOfferEmployee>();
        }
    
        public int FreelancerID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public int SkillID { get; set; }
        public int AddressID { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual ICollection<HiringOfferEmployee> HiringOfferEmployee { get; set; }
    }
}
