//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerHR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiringOfferEmployee
    {
        public int HiringBussinessID { get; set; }
        public int FreelancerID { get; set; }
        public decimal HourlyRate { get; set; }
    
        public virtual Freelancer Freelancer { get; set; }
        public virtual HiringOffer HiringOffer { get; set; }
    }
}
