//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerHR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiringOffer : HiringRequest
    {
        public HiringOffer()
        {
            this.HiringOfferEmployee = new HashSet<HiringOfferEmployee>();
        }
    
        public int Discount { get; set; }
        public int EmployeeInChargeID { get; set; }
        public int HiringRequestID { get; set; }
    
        public virtual HiringRequest HiringRequest1 { get; set; }
        public virtual ICollection<HiringOfferEmployee> HiringOfferEmployee { get; set; }
    }
}
