//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelancerHR.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FreelancerHiringEntities : DbContext
    {
        public FreelancerHiringEntities()
            : base("name=FreelancerHiringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HiringRequest> HiringRequest { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Freelancer> Freelancer { get; set; }
        public virtual DbSet<Compagny> Compagny { get; set; }
        public virtual DbSet<HiringOfferEmployee> HiringOfferEmployee { get; set; }
    }
}
